server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**

        - id: faculty-service
          uri: lb://FACULTY-SERVICE
          predicates:
            - Path=/faculty/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
