server:
  port: 8082
logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl: WARN
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/course_service
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
